backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

i18n:
  locales: [uk, de]
  default_locale: uk

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index.{{locale}}"
    i18n:
      structure: multiple_files
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false, i18n: false }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

  - name: "schedule"
    label: "Schedule"
    folder: "content/schedule"
    create: false
    i18n:
      structure: multiple_files
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

  - name: "sponsors"
    label: "Sponsors"
    folder: "content/sponsors"
    create: false
    i18n:
      structure: multiple_files
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

  - name: "contacts"
    label: "Contacts"
    folder: "content/contacts"
    create: false
    i18n:
      structure: multiple_files
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }